#!/usr/bin/env bash
# ==============================================================================
# One-time 6-gram KenLM + unigrams (feeds S3).
#
# NOT WIRED — by design. Per Q2/RP1 the LM assets are PRE-COPIED into
# data/lm/ (court_6gram.bin + unigrams.txt), so the pipeline never rebuilds them,
# and asrpipe.lm.build_lm was left as a stub (not ported). This script only checks
# that the assets are present. To actually rebuild the LM, use the original tool in
# the frozen tree: /workspace/code/build_ngram_lm.py (+ /workspace/code/kenlm).
# ==============================================================================
set -euo pipefail
cd /workspace/code2

LM=data/lm
ok=1
for f in court_6gram.bin unigrams.txt; do
  if [ -s "$LM/$f" ]; then echo "  present: $LM/$f ($(du -h "$LM/$f" | cut -f1))"; else echo "  MISSING: $LM/$f"; ok=0; fi
done
if [ "$ok" = 1 ]; then
  echo "LM assets present — nothing to build (Q2: pre-copied, not regenerated by code2)."
else
  echo "LM assets missing. Rebuild via /workspace/code/build_ngram_lm.py, then copy into $LM/." >&2
  exit 1
fi
